name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
  schedule:
    - cron: "0 0 * * *"

jobs:

  linux-jvm-tests:
    name: JDK ${{matrix.java-version}} JVM Tests
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 13, 15]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
      - name: Tests
        run: mvn install
      - name: Integration tests
        run: mvn verify -f integration-tests

  native-tests:
    needs: [linux-jvm-tests]
    name: Native Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Tests
        run: mvn install
      - name: Integration tests
        run: mvn verify -Pnative-image -f integration-tests
